name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whichever branch you deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    # --- ADD THIS SECTION ---
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # --- END OF ADDED SECTION ---
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Firebase App ID
        run: |
          sed -i "s|__FIREBASE_APP_ID_PLACEHOLDER__|${{ secrets.FIREBASE_APP_ID }}|g" index.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
